version: '3.8'
services:
  app:
    # The GitHub Action will automatically replace LATEST_HASH with the real ID
    image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/roothealth-dashboard:LATEST_HASH
    ports:
      - "80:8080"
    restart: always